"""Deterministic Markdown reporting for ML experiments."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


def _fmt(value: object) -> str:
    if isinstance(value, float):
        return "NA" if pd.isna(value) else f"{value:.6f}"
    return str(value)


def _markdown_table(frame: pd.DataFrame) -> str:
    """Render a small table without requiring the optional tabulate package."""
    columns = list(frame.columns)
    header = "| " + " | ".join(map(str, columns)) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    body = ["| " + " | ".join(_fmt(row[c]) for c in columns) + " |" for _, row in frame.iterrows()]
    return "\n".join([header, separator, *body])


def write_research_report(
    path: Path,
    *,
    summary: dict,
    bootstrap: dict,
    stability: dict,
    regime_table: pd.DataFrame,
    threshold_table: pd.DataFrame,
    model_table: pd.DataFrame,
    cost_table: pd.DataFrame,
    importance_table: pd.DataFrame,
    calibration_table: pd.DataFrame,
    manifest: dict,
) -> None:
    rows = ["# Small-Sample Option ML Research Report", "", "## Out-of-sample results", ""]
    rows += [f"- **{key}**: {_fmt(value)}" for key, value in summary.items()]
    rows += ["", "## Block-bootstrap uncertainty", ""]
    rows += [f"- **{key}**: {_fmt(value)}" for key, value in bootstrap.items()]
    rows += ["", "## Fold stability", ""]
    rows += [f"- **{key}**: {_fmt(value)}" for key, value in stability.items()]
    rows += ["", "## Performance by market regime", "", _markdown_table(regime_table)]
    rows += ["", "## Probability-threshold sensitivity", "", _markdown_table(threshold_table)]
    rows += ["", "## Probability-model comparison", "", _markdown_table(model_table)]
    rows += ["", "## Transaction-cost stress", "", _markdown_table(cost_table)]
    rows += ["", "## Logistic feature importance", "", _markdown_table(importance_table)]
    rows += ["", "## Probability calibration", "", _markdown_table(calibration_table)]
    rows += [
        "",
        "## Methodology and limitations",
        "",
        "All reported model predictions are generated by expanding walk-forward folds. "
        "Preprocessing, PCA, regime estimation, and classification are refitted inside each fold. "
        "An embargo separates training and test dates; exit-date purging is used when available.",
        "",
        "The history is short. Results are research evidence, not proof of future profitability. "
        "A strategy should not be promoted unless improvements are stable across folds, remain after "
        "costs, and have bootstrap intervals that exclude materially poor outcomes.",
        "",
        "## Reproducibility manifest",
        "",
        "```json",
        json.dumps(manifest, ensure_ascii=False, indent=2, default=str),
        "```",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")
